let songs = [
    {
        id: "1",
        name: "Phóng Đổ Tim Em",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - Phóng Đổ Tim Em - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "2",
        name: "CALL ME",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - CALL ME - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "3",
        name: "Cầu Vĩnh Tuy",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - Cầu Vĩnh Tuy - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "4",
        name: "Từng Quen",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/TỪNG QUEN - WREN EVANS X LIM FENG.mp3",
    },
    {
        id: "5",
        name: "bé ơi từ từ",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - bé ơi từ từ - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "6",
        name: "Lối Chơi (Interlude)",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics//WREN EVANS - Lối Chơi (Interlude) - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "7",
        name: "Tình Yêu Vĩ Mô",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - Tình Yêu Vĩ Mô - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "8",
        name: "Việt Kiều",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - VIỆT KIỀU (ft. itsnk, starring @oanhdaqueen) - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "9",
        name: "ĐĐĐ",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - ĐĐĐ - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "10",
        name: "Quyền Anh",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - Quyền Anh - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "11",
        name: "Tò Te Tí",
        artist: "Wren Evans, itsnk",
        album: "LOI CHOI: The Leo Pop Punk",
        image: "../Images/loiChoi.jfif",
        path: "../Musics/WREN EVANS - Tò Te Tí - LOI CHOI The First Album (ft. itsnk).mp3",
    },
    {
        id: "12",
        name: "00",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/00.mp3",
    },
    {
        id: "13",
        name: "Chìm Sâu",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/Chìm Sâu - RPT MCK (feat. Trung Trần) - Official Lyrics Video.mp3",
    },
    {
        id: "14",
        name: "Suit & Tie",
        artist: "RPT MCK, Hoàng Tôn",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/03. Suit & Tie - RPT MCK ( ft. Hoàng Tôn ) - - 99_ - the album.mp3",
    },
    {
        id: "15",
        name: "Va Vào Giai Điệu Này",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/04. Va Vào Giai Điệu Này - RPT MCK - -99_- the album.mp3",
    },
    {
        id: "16",
        name: "Tối Nay Ta Đi Đâu Nhờ",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/Tối Nay Ta Đi Đâu Nhờ.mp3",
    },
    {
        id: "17",
        name: "Chỉ Một Đêm Nữa Thôi",
        artist: "RPT MCK, tlinh",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/06. Chỉ Một Đêm Nữa Thôi - RPT MCK ( ft. tlinh ) - - 99_ - the album.mp3",
    },
    {
        id: "18",
        name: "Thôi Em Đừng Đi",
        artist: "RPT MCK, Trung Trần",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/07. Thôi Em Đừng Đi - RPT MCK ( ft. Trung Trần ) - - 99_ - the album.mp3",
    },
    {
        id: "19",
        name: "50/50",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/50-50.mp3",
    },
    {
        id: "20",
        name: "Cuốn Cho Anh Một Điếu Nữa Đi",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/09. Cuốn Cho Anh Một Điếu Nữa Đi - RPT MCK - - 99_ - the album.mp3",
    },
    {
        id: "21",
        name: "Show Me Love",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/10. Show Me Love - RPT MCK - - 99_ - the album.mp3",
    },
    {
        id: "22",
        name: "Tại Vì Sao",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/RPT MCK - TẠI VÌ SAO - Official Music Video.mp3",
    },
    {
        id: "23",
        name: "Thờ Er",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/Thờ Er.mp3",
    },
    {
        id: "24",
        name: "Ai Mới Là Kẻ Xấu Xa",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/RPT MCK - AI MỚI LÀ KẺ XẤU XA - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "25",
        name: "Anh Đã Ổn Hơn",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/14. Anh Đã Ổn Hơn - RPT MCK - -99_- the album.mp3",
    },
    {
        id: "26",
        name: "Badtrip",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/15. Badtrip - RPT MCK - -99_- the album.mp3",
    },
    {
        id: "27",
        name: "99",
        artist: "RPT MCK",
        album: "99%",
        image: "../Images/99percent.jfif",
        path: "../Musics/16. 99 - RPT MCK - -99_- the album.mp3",
    },
    {
        id: "28",
        name: "tình yêu có nghĩa là gì?",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - tình yêu có nghĩa là gì- (intro) - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "29",
        name: "người đẹp ngủ",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - người đẹp ngủ - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "30",
        name: "người điên",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - người điên - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "31",
        name: "kho báu đánh rơi (feat. GREY D)",
        artist: "tlinh, GREY D",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - kho báu đánh rơi (feat. Grey D) - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "32",
        name: "ái",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - ái (interlude) - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "33",
        name: "làm lành chữa tình",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - làm lành chữa tình - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "34",
        name: "thế giới thần tiên",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - thế giới thần tiên - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "35",
        name: "những đốm sáng",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - những đốm sáng - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "36",
        name: "nữ siêu anh hùng",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - nữ siêu anh hùng - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "37",
        name: "ghệ iu dấu của em ơi",
        artist: "tlinh, 2pillz, WOKEUP",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - ghệ iu dấu của em ơi - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "38",
        name: "nếu lúc đó",
        artist: "tlinh, 2pillz",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - nếu lúc đó - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "39",
        name: "kết thúc = mở đầu",
        artist: "tlinh",
        album: "ái",
        image: "../Images/ai.jfif",
        path: "../Musics/tlinh - kết thúc = mở đầu (outro) - OFFICIAL VISUALIZER.mp3",
    },
    {
        id: "40",
        name: "Intro",
        artist: "MONO",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/INTRO.mp3",
    },
    {
        id: "41",
        name: "Buông",
        artist: "MONO",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Buông (Album 22 - Track No.02).mp3",
    },
    {
        id: "42",
        name: "Em Là",
        artist: "MONO, Onionn.",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Em Là (Album 22 - Track No.03).mp3",
    },
    {
        id: "43",
        name: "Kill Me",
        artist: "MONO",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Kill Me (Album 22 - Track No.04).mp3",
    },
    {
        id: "44",
        name: "Quên Anh Đi",
        artist: "MONO",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Quên Anh Đi (Album 22 - Track No.05).mp3",
    },
    {
        id: "45",
        name: "Anh Không Thể",
        artist: "MONO, Onionn.",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Anh Không Thể (Album 22 - Track No.07).mp3",
    },
    {
        id: "46",
        name: "Do You",
        artist: "MONO, Rein, Onionn.",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO ft Rein - Do You (Album 22 - Track No.08).mp3",
    },
    {
        id: "47",
        name: "Cô nương Ahhhh~",
        artist: "MONO",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/_MONO - Cô Nương AHHHhhhh. (Album 22 - Track No.09).mp3",
    },
    {
        id: "48",
        name: "Waiting For You",
        artist: "MONO, Onionn.",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - Waiting For You (Album 22 - Track No.10).mp3",
    },
    {
        id: "49",
        name: "L.I.E",
        artist: "MONO, Onionn.",
        album: "22",
        image: "../Images/22.jfif",
        path: "../Musics/MONO - L.I.E (Album 22 - Track No.11).mp3",
    },
    {
        id: "50",
        name: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Ai Cũng Phải Bắt Đầu Từ Đâu Đó (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "51",
        name: "Giờ Thì Ai Cười",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Giờ Thì Ai Cười (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "52",
        name: "Không Phải Gu",
        artist: "HIEUTHUHAI, B Ray, Tage",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Không Phải Gu (prod. by Kewtiie) ft. B Ray & Tage [Official Lyric Video].mp3",
    },
    {
        id: "53",
        name: "Siêu Sao",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Siêu Sao (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "54",
        name: "Đi Họp Lớp",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Đi Họp Lớp (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "55",
        name: "Không Thể Say",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Không Thể Say (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "56",
        name: "Exit Sign",
        artist: "HIEUTHUHAI, marzuz",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Exit Sign (prod. by Kewtiie) ft. marzuz [Official Lyric Video].mp3",
    },
    {
        id: "57",
        name: "Visa Interlude",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Visa Interlude (prod. by Kewtiie) [Official Audio].mp3",
    },
    {
        id: "58",
        name: "Sắp Nổi Tiếng",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Sắp Nổi Tiếng (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "59",
        name: "KPI",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - KPI (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "60",
        name: "Everything Will Be Okay",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Everything Will Be Okay (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "61",
        name: "Cho Em An Toàn",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - Cho Em An Toàn (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "62",
        name: "NOLOVENOLIFE",
        artist: "HIEUTHUHAI",
        album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
        image: "../Images/aiCungPhai.jfif",
        path: "../Musics/HIEUTHUHAI - NOLOVENOLIFE (prod. by Kewtiie) [Official Lyric Video].mp3",
    },
    {
        id: "63",
        name: "Intro",
        artist: "MONO",
        album: "Đẹp",
        image: "../Images/dep.jfif",
        path: "../Musics/Intro1.mp3",
    },
    {
        id: "64",
        name: "Cười Lên",
        artist: "MONO",
        album: "Đẹp",
        image: "../Images/dep.jfif",
        path: "../Musics/MONO - CƯỜI LÊN (Official Audio).mp3",
    },
    {
        id: "65",
        name: "Em Xinh",
        artist: "MONO, Onionn.",
        album: "Đẹp",
        image: "../Images/dep.jfif",
        path: "../Musics/MONO - Em Xinh (Official Music Video).mp3",
    },
    {
        id: "66",
        name: "Young",
        artist: "MONO",
        album: "Đẹp",
        image: "../Images/dep.jfif",
        path: "../Musics/MONO - Young (Official Music Video).mp3",
    },
    {
        id: "67",
        name: "Open Your Eyes",
        artist: "MONO, Onionn.",
        album: "Đẹp",
        image: "../Images/dep.jfif",
        path: "../Musics/MONO - 'OPEN YOUR EYES (Official Audio).mp3",
    },
    {
        id: "68",
        name: "Chúng Ta Của Tương Lai",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/chungTaCuaTuongLai.jfif",
        path: "../Musics/SƠN TÙNG M-TP - CHÚNG TA CỦA TƯƠNG LAI - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "70",
        name: "MAKING MY WAY",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/MAKINGMYWAY.jfif",
        path: "../Musics/making-my-way-son-tung-m-tp.mp3",
    },
    {
        id: "71",
        name: "THERE'S NO ONE AT ALL",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/THERE'SNOONEATALL.jfif",
        path: "../Musics/SƠN TÙNG M-TP - THERES NO ONE AT ALL (ANOTHER VERSION) - OFFICIAL MUSIC VIDEO.mp3",

    },
    {
        id: "72",
        name: "Muộn Rồi Mà Sao Còn",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/muonRoiMaSaoCon.jfif",
        path: "../Musics/SƠN TÙNG M-TP - MUỘN RỒI MÀ SAO CÒN - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "73",
        name: "Chúng Ta Của Hiện Tại",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/chungTaCuaHienTai.jfif",
        path: "../Musics/Chúng Ta Của Hiện Tại.mp3",
    },
    {
        id: "74",
        name: "Có Chắc Yêu Là Đây",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/coChacYeuLaDay.jfif",
        path: "../Musics/SƠN TÙNG M-TP - CÓ CHẮC YÊU LÀ ĐÂY - OFFICIAL MUSIC VIDEO.mp3",
    },
    {
        id: "75",
        name: "Hãy Trao Cho Anh",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/hayTraoChoAnh.jfif",
        path: "../Musics/SƠN TÙNG M-TP - HÃY TRAO CHO ANH ft. Snoop Dogg - Official MV.mp3",
    },
    {
        id: "76",
        name: "Chạy Ngay Đi",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/chayNgayDi.jfif",
        path: "../Musics/CHẠY NGAY ĐI - RUN NOW - SƠN TÙNG M-TP - Official Music Video.mp3",
    },
    {
        id: "77",
        name: "Lạc Trôi",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/lacTroi.jfif",
        path: "../Musics/LẠC TRÔI - OFFICIAL MUSIC VIDEO - SƠN TÙNG M-TP.mp3",
    },
    {
        id: "78",
        name: "Nơi Này Có Anh",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/noiNayCoAnh.jfif",
        path: "../Musics/NƠI NÀY CÓ ANH - OFFICIAL MUSIC VIDEO - SƠN TÙNG M-TP.mp3",
    },
    {
        id: "79",
        name: "Chúng Ta Không Thuộc Về Nhau",
        artist: "Sơn Tùng M-TP",
        album: "Sơn Tùng M-TP",
        image: "../Images/chungTaKhongThuocVeNhau.jfif",
        path: "../Musics/Chúng Ta Không Thuộc Về Nhau - Official Music Video - Sơn Tùng M-TP.mp3",
    },
];
const storedSongs = localStorage.getItem("songs");

// Nếu dữ liệu không tồn tại trong localStorage, lưu dữ liệu mặc định vào đó
if (!storedSongs) {
    localStorage.setItem("songs", JSON.stringify(songs));
}

